### ISSUE TITLE
Can you write some examples?

### ISSUE THREAD

**Issue by mrlogick** [KmolYuan/metaheuristics-nature-rs#6]
As I just started learning genetic algorithms, it's not very clear to me how to use this crate.
It would be good to have a simple example, like the Knapsack Problem, or something.

**Comment by KmolYuan** [comment]
I have a small example at <https://docs.rs/metaheuristics-nature/latest/metaheuristics_nature/struct.Fx.html>.

The algorithm will try to minimize the function's return value, and `bound` is the range of the variables.

```rust
use metaheuristics_nature::{Fx, Rga, Solver};

let bound = [[-50., 50.]; 4];
let f = Fx::new(&bound, |&[a, b, c, d]| a * a + 8. * b * b + c * c + d * d);
let s = Solver::build(Rga::default(), f)
    .seed(0)
    .task(|ctx| ctx.gen == 20)
    .solve();
```

Currently, this crate does not support integer problems. The a, b, c, and d are real numbers (`f64`).

**Comment by mrlogick** [comment]
Ok, it's clearer now, thanks!
